## Estructuras de datos: Listas

#### Lista

La primera estructura de datos que veremos son las **listas**. Éstas son un conjunto de elementos separados por comas y escritos entre corchetes, `[]`.

Las listas son:
  * heterogéneas: los elementos pueden ser de distinto tipo en una misma lista.
  * mutables: los elementos pueden ser modificados.

Un ejemplo de lista sería

In [1]:
l = ['Juan', 31, 172.32, True]
print(l)

['Juan', 31, 172.32, True]


In [2]:
type(l)

list

##### Tamaño de una lista

Para saber la longitud o el tamaño de una lista, podemos hacer uso de la función `len()`

In [3]:
l = [1, 2, 3, 4, 5, 6, 7, 8, 9]
len(l)

9

In [4]:
l = ['Zoe', 'Pablo', 'Miguel', 'Silvia']
len(l)

4

##### Elementos de una lista

Cada elemento en una lista tiene su propio índice

In [5]:
names = ['Maria', 'Juan', 'Claudia', 'Jorge', 'Avelina']

A `María` le corresponde el índice 0; a `Juan`, el 1; a `Claudia` el 2; a `Jorge`, el 3; y a `Avelina, el 4.

**¡Cuidado!** En `Python`, los índices siempre empiezan en 0. De este modo, al primer elemento le corresponde el índice 0; al segundo el índice 1; y al n-ésimo, le corresponde el índice n - 1.

Dada una lista, podemos acceder a sus elementos utilizando la sintaxis `[]`.

In [6]:
print(names[0])

Maria


In [7]:
print(names[3])

Jorge


In [8]:
print(names[5])

IndexError: list index out of range

**¡Cuidado!** Si dada una lista llamamos a un elemento cuyo índice no existe para dicha lista, `Python` automáticamente nos devolverá un error.

Podemos acceder a los últimos elementos de la lista haciendo uso de índices negativos.

In [9]:
print(names[-1]) # Último elemento

Avelina


In [10]:
print(names[-3]) # Tercer elemento empezando por el final

Claudia


Si en vez de querer acceder a los elementos uno por uno estamos interesados en acceder a varios elementos a la vez, podemos hacer uso de la función `:`

In [11]:
print(names[2:4])

['Claudia', 'Jorge']


In [12]:
print(names[:3])

['Maria', 'Juan', 'Claudia']


In [13]:
print(names[3:])

['Jorge', 'Avelina']


**Observación.** En cuanto a la función `:`
  * El índice indicado a la derecha de los `:` nunca es incluido.
  * Si no indicamos elementos a la izquierda de los `:`, por defecto `Python` interpreta que se trata del 0.
  * Si no indicamos elementos a la derecha, por defecto `Python` interpreta que debe mostrar los elementos desde el índice indicado a la izquierda hasta el último.

Además de acceder, podemos modificar los elementos de una lista.

In [14]:
names[0] = 'Marina'
names[3] = 'Jaime'
names

['Marina', 'Juan', 'Claudia', 'Jaime', 'Avelina']

Podemos añadir nuevos elementos a una lista con el método `.append()`

In [15]:
names = ['Maria', 'Cristina', 'Juana']
print( names )

names.append('Andrea')
names.append('Ana')
print( names )

['Maria', 'Cristina', 'Juana']
['Maria', 'Cristina', 'Juana', 'Andrea', 'Ana']


**Observación.** Los elementos añadidos con el método `.append()`, se incluyen al final.

Si quisieramos añadir un nuevo elemento a una lista, pero no lo quisiéramos al final, sino en una posición específica, entonces utilizaremos el método `.insert()` al primero le indicamos al índice donde queremos posicionar el nuevo elemento y, en segundo lugar, indicamos dicho nuevo elemento.

In [16]:
names = ['Mario', 'Cristian', 'Juan']
print( names )

names.insert(1, 'Andrés')
print( names )
names.insert(3, 'Miguel')
print(names)

['Mario', 'Cristian', 'Juan']
['Mario', 'Andrés', 'Cristian', 'Juan']
['Mario', 'Andrés', 'Cristian', 'Miguel', 'Juan']


**Observación**. Cuando le indicamos que queremos el elemento `Andrés` en el índice 1, el que antes ocupaba dicho índice, `Cristian`, pasa a ocupar el siguiente, 2, y así con el resto de elementos que van a continuación.

##### Ejercicio

Vamos a pedirle al usuario la longitud de una lista y haremos que introduzca por teclado tantos números enteros como haya indicado, que se guardarán en una lista. Al acabar, imprimiremos la lista.

In [17]:
n = int(input('Introduce el tamaño de la lista: '))
l = []

for i in range(n):
  l.append(int(input()))

print(f'Tu lista es: {l}')

Tu lista es: [1, 2, 3, 4, 5]


#### Bucles con listas

Si quisieramos imprimir por pantalla todos los elementos de una lista, lo podríamos hacer mediante los índices

In [18]:
for i in range(len(names)):
  print(names[i])

Mario
Andrés
Cristian
Miguel
Juan


o mucho más fácilmente iterando la lista con un `for` con la siguiente sintaxis:

In [19]:
for i in names:
  print( i )

Mario
Andrés
Cristian
Miguel
Juan


#### Concatenación de listas

Dadas dos o más listas, podemos concatenarlas haciendo uso de la función `+`

In [20]:
l1 = [True, 21, 'Marta']
l2 = [22.5, False, 22, 'Rafa']
print( l1 + l2 )

[True, 21, 'Marta', 22.5, False, 22, 'Rafa']


#### Repetición de listas

Podemos repetir una misma lista tantas veces como queramos con la función `*`

In [21]:
abc = ['A', 'B', 'C']
print( abc * 5 )

['A', 'B', 'C', 'A', 'B', 'C', 'A', 'B', 'C', 'A', 'B', 'C', 'A', 'B', 'C']


#### Lista vacía

In [22]:
empty_list = []
print(len(empty_list))

0


#### Más métodos de listas

El método `.count()` recibe un elemento como argumento y cuenta la cantidad de veces que aparece en la lista

In [23]:
numbers = [0, 1, 1, 2, 2, 2, 3, 3, 3, 3]

counted = []
for element in numbers:
  if element not in counted:
    counted.append(element)
    print(f'El element {element} aparece {numbers.count(element)} veces')

El element 0 aparece 1 veces
El element 1 aparece 2 veces
El element 2 aparece 3 veces
El element 3 aparece 4 veces


El método `.extend()` extiende la lista agregando al final el iterable indicado por parámetro.

In [24]:
numbers = [1,2,3,4,5]
numbers.extend([6])
numbers.extend([7, 8])
numbers.extend(range(9, 16))
print(numbers)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]


**Observación.** Un iterable es un objeto de `Python` capaz de devolver sus elementos uno por uno, permitiendo ser iterado en un bucle for. De momento solo conocemos las listas y el resultado de `range()`, pero en secciones futuras veremos los diccionarios, las tuplas y los conjuntos, que también son conjuntos iterables.

El método `index()` recibe un elemento como argumento y devuelve el índice de la primera aparición en la lista.

In [30]:
numbers = [0, 1, 1, 2, 2, 2, 3, 4, 3, 4]
print(numbers.index(2))
print(numbers.index(4))

3
7


In [27]:
print(numbers.index(7))

ValueError: 7 is not in list

El método `.pop()` devuelve el último elemento de la lista y lo borra de la misma.

In [31]:
print( numbers )
# print(numbers.pop())
# print(numbers)

for i in range(5):
  print( numbers.pop() )
  print( numbers )

[0, 1, 1, 2, 2, 2, 3, 4, 3, 4]
4
[0, 1, 1, 2, 2, 2, 3, 4, 3]
3
[0, 1, 1, 2, 2, 2, 3, 4]
4
[0, 1, 1, 2, 2, 2, 3]
3
[0, 1, 1, 2, 2, 2]
2
[0, 1, 1, 2, 2]


El método `.remove()` recibe como argumento un elemento y borra su primera aparación de la lista.

In [32]:
numbers = [0, 1, 2, 4, 3, 4, 5, 6, 7]
numbers.remove(4)
print(numbers)

[0, 1, 2, 3, 4, 5, 6, 7]


El método `.reverse()` devuelve la lista en orden inverso.

In [34]:
numbers = [1, -1, 2, -2, 3, -3]
numbers.reverse()
print(numbers)

[-3, 3, -2, 2, -1, 1]


El método `.sort()` devuelve la lista en orden

In [35]:
numbers = [1, 3, 5, 2, 4]
numbers.sort()
print(numbers)

[1, 2, 3, 4, 5]


Si quisiésemos ordenar los elementos en orden decreciente, podríamos hacer uso del parámetro `reverse` del método `.sort()`:

In [36]:
numbers = [1, 3, 5, 2, 4]
numbers.sort(reverse = True)
print(numbers)

[5, 4, 3, 2, 1]


**Observación.** De momento solo conocemos las listas y el resultado de `range()`, pero en secciones futuras veremos los diccionarios, las tuplas y los conjuntos, que también son objetos iterables.

#### Conversión a listas

Para convertir un objeto iterable de `Python` a lista, hay que usar la función `list()`

In [37]:
print(type(range(0, 100, 10)))

<class 'range'>


In [38]:
print(list(range(0, 100, 10)))

[0, 10, 20, 30, 40, 50, 60, 70, 80, 90]


In [39]:
print(type(list(range(0, 100, 10))))

<class 'list'>


#### Listas anidadas

Las listas anidadas son listas desntro de listas. Es decir, las listas no solo pueden contener números, strings o datos booleanos, sino que también pueden contener otras listas.

##### Ejemplo 1

A continuación mostramos una lista anidada, pues consta de 3 elementos:

  * 1 lista de 3 strings.
  * 1 lista heterogénea de 3 elementos que a su vez contiene una lista con 5 números.
  * 1 número.

In [40]:
l = [['Maria', 'Santos', 'Fernández'], ['Juan', [1, 2, 3, 4, 5], 32], 2]

Para acceder a un elemento, necesitamos indicar su índice. Si un elemento está en una lista dentro de una lista dentro de una lista dentro de una lista, en primer lugar indicamos el índice de la lista exterior dentro de `[]`; después, el índice de la siguiente lista más exterior también entre `[]`; y por último, el índice de la lista más interna, claramente también entre `[]`.

Accedamos al string `Fernández` y luego al número `5`.

In [41]:
print(l[0][2]) # Fernández
print(l[1][1][4]) # 5

Fernández
5


#### Matrices

Hay un tipo muy utilizado de listas anidadas. Se caracterzia por ser una lista de m listas, donde cada una de las listas tiene el mismo número de elementos, n. A este tipo de listas se les conoce como matrices.

In [2]:
matrix = [[1,2,3], [4,5,6], [7,8,9]]

En matemáticas, las matrices, se definen del siguiente modo.

**Matriz**. Una matriz de dimensiones m X n es una tabla formada por elementos dispuestos en m filas y n columnas de la forma.

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/6222e9f1577287b35d8c10bdb1a8018dcb46a934)

Los elemtnos de la matriz se representan con doble subíndice, aij, donde el primero indica a la fila a la que pertenece y, el segundo, la columna.

Entonces, la matriz que hemos definido anteriormente.

In [3]:
matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

Escrita en forma de tabla sería: `matrix` = ![](https://i.ytimg.com/vi/TQK3y5eZzYo/hqdefault.jpg)

Para acceder a los elementos de una matriz en `Python`, utilizamos la sintaxis `[][]`, donde primero indicamos la fila y, a continuación, la columna.

In [4]:
matrix[0][2]

3

In [5]:
matrix[1][1]

5

In [6]:
matrix[2][0]

7

Podemos mostrar una matriz de `Python` en forma de tabla con un bucle `for`, del siguiente modo

In [7]:
for row in matrix: # Acedemos a las filas de la matrix
  print(row)

[1, 2, 3]
[4, 5, 6]
[7, 8, 9]


Si lo que queremos es mostrar todos los elementos de la matriz en columna, podemos utilizar dos bucles `for` anidados del siguiente modo:

In [10]:
for row in matrix: # Accedemos a las filas
  for element in row: # Accedemos a los elementos de las filas
    print(element)

1
2
3
4
5
6
7
8
9


Si lo que queremos es mostrar la matriz en forma de tabla, sin comas, ni corchetes por en medio, lo podemos hacer de dos formas:

  * Haciendo uso de las dimensiones de la matriz, y por tanto, de la función `range()`
  * Sin hacer uso de las dimensiones

La primera forma sería:

In [11]:
# m es el número de filas y n, el de columnas
m = len(matrix)
n = len(matrix[0])

for i in range(m):
  for j in range(n):
    print(matrix[i][j], end = ' ')
  print('')

1 2 3 
4 5 6 
7 8 9 


**Observación.**

  1. Como todas las filas tienen el mismo número de elementos, nos da igual si calculamos n con la primera fila o con cualquiera otra.
  2. Hemos hecho uso del parámetro `end` de la función `print()` para indicar si, en vez de un salto de línea como ocurre por defecto, queremos que suceda otra cosa inmediatamente después de ejecutar la función `print()`. En este caso, hemos indicado que queremos un espacio en blanco.

Y la segunda forma, es la siguiente:

In [12]:
for row in matrix:
  for element in row:
    print(element, end = ' ')
  print('')

1 2 3 
4 5 6 
7 8 9 


#### Suma de matrices

Para poder sumar dos matrices, necesitamos que tengan la misma dimensión. Entonces, dadas A y B dos matrices con dimensión m X n, su suma será una matriz de dimensión m X n y sus elementos se obtienen del siguiente modo:

![](https://cdn.discordapp.com/attachments/973427374077141022/1039674872932093962/image.png)

Dadas dos matrices con la misma dimensión, las podemos usar haciendo uso de bucles `for` anidados.

In [1]:
A = [[1, 0, -3], [2, 0, 1], [-1, -1, 0]]
B = [[-1, -2, 0], [-2, 3, 0], [0, 0, -3]]

m = len(A)
n = len(A[0])

if len(A) == len(B) and len(A[0]) == len(B[0]):
  C =[]

  for i in range(m):
    C.append([])
    for j in range(n):
      C[i].append(A[i][j] + B[i][j])

  print(C)

else:
  print('No se puede realizar la suma, pues las dimensiones de las matrices no coinciden')

[[0, -2, -3], [0, 3, 1], [-1, -1, -3]]


El resultado de sumas las atrices A y B ha sido

![](https://cdn.discordapp.com/attachments/973427374077141022/1039787530905714708/image.png)

In [2]:
for row in C:
  print(row)

[0, -2, -3]
[0, 3, 1]
[-1, -1, -3]


**Observación.** Hemos puesto un `if` que, suponiendo que tanto A como B son matrices, comprueba si sus dimensiones coinciden. De ser cierto, procede a hacer la suma. De lo contrario, devuelve un mensaje indicando que la suma no puede llevarse a cabo.

#### Producto de matrices

Para poder multiplicar matrices, necesitamos que la matriz de la izquierda tenga el mismo número de columnas que número de columnas que número de filas tiene la matriz de la derecha. Entonces, dadas las matrices A y B de dimensiones m X n y n X p respectivamente, su producto será una matriz de dimensión m X p y se obtiene del siguiente modo:

![](https://cdn.discordapp.com/attachments/973427374077141022/1039788371054166016/image.png)

Dadas dos matrices, la primera con el mismo número de columnas que filas tiene la segunda, podemos multiplicarlas del siguiente modo:

In [3]:
A = [[1, 0, -3, 2], [2, 0, 1, 1], [-1, 0, -1, 0]]
B = [[-1, -2, 0], [-2, 3, 0], [0, 0, -3], [1, 1, -1]]

m, n, p = len(A), len(B), len(B[0])

C = []

for i in range(m):
  C.append([])
  for j in range(p):
    elemento = 0
    for k in range(n):
      elemento = elemento + A[i][k] * B[k][j]
    C[i].append(elemento)

El resultado de multiplicar las matrices A y B ha sido:

![](https://cdn.discordapp.com/attachments/973427374077141022/1039790228006768681/image.png)

In [4]:
for row in C:
  print( row )

[1, 0, 7]
[-1, -3, -4]
[1, 2, 3]


#### Matrices con `numpy`

Existe una forma más sencilla de trabajar con matrices y es gracias a la librería `numpy`. Para importarla, simplemente hay que ejecutar la siguiente línea de código.

In [2]:
import numpy as np

Para crear una matriz vacía, usamos el método `.empty()`, al que le indicamos por parámetro las dimensiones.

In [3]:
A = np.empty((2, 3)) # 2 filas y 3 columnas
print( A )

[[4.6406002e-310 0.0000000e+000 0.0000000e+000]
 [0.0000000e+000 0.0000000e+000 0.0000000e+000]]


Para crear una matriz vacía con las mismas dimensiones de otra matriz definida anteriormente, usamos el método `.empty_like()`, al que le indicamos por parámetro la matriz existente

In [4]:
B = np.empty_like(A) # Tendrá 2 filas y 3 columnas
print( B )

[[4.6406002e-310 0.0000000e+000 0.0000000e+000]
 [0.0000000e+000 0.0000000e+000 0.0000000e+000]]


Para crear una matriz nula, usmaos el método `.zeros()`, al que le indicamos por parámetro las dimensiones

In [5]:
C = np.zeros((3, 5)) # Matriz nula de dimensiones 3 x 5
print( C )

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


Para crear una matriz de ceros con las mismas dimensiones de otra matriz definida anteriormente, usamos el método `.zeros_like()`, al que le indicamos por parámetro la matriz existente

In [7]:
D = np.zeros_like(A) # Tendrá 2 filas y 3 columnas y todos sus elementos valdrán 0
print( D )

[[0. 0. 0.]
 [0. 0. 0.]]


Para crear una matriz de unos con las mismas dimensiones de otra matriz definida anteriormente, usamos el método `.ones_like()`, al que le indicmoas por parámetro la matriz existente

In [8]:
F = np.ones_like(C) # Tendrá 3 filas y 5 columnas y todos sus elementos valdrán 1
print( F )

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


Podemos crear matrices de numpy a partir de listas con el método `.matrix()`

In [9]:
M = np.matrix([[1, 0, -3, 2], [2, 0, 1, 1], [-1, 0, -1, 0]])
print( M )

[[ 1  0 -3  2]
 [ 2  0  1  1]
 [-1  0 -1  0]]


Para saber las dimensiones de una matriz, podemos utilizar el método `.shape`

In [10]:
M.shape

(3, 4)

Ahora es más sencillo sumar matrices, pues solamente necesitamos la función `+`

In [11]:
A = np.matrix([[1, 0, -3], [2, 0, 1], [-1, -1, 0]])
B = np.matrix([[-1, -2, 0], [-2, 3, 0], [0, 0, -3]])
matrixSum = A + B
matrixSum

matrix([[ 0, -2, -3],
        [ 0,  3,  1],
        [-1, -1, -3]])

También es más sencillo hacer el producto matricial A * B con el método `.dot()`

In [12]:
A = np.matrix([[1, 0, -3, 2], [2, 0, 1, 1], [-1, 0, -1, 0]])
B = np.matrix([[-1, -2, 0,], [-2, 3, 0], [0, 0, -3], [1, 1, -1]])

matrixProd = A.dot(B)
matrixProd

matrix([[ 1,  0,  7],
        [-1, -3, -4],
        [ 1,  2,  3]])

Gracias a `numpy`, también es mucho más sencillo mostrar una matriz en forma de tabla, pues nos basta con hacer uso de la función `print()`:

In [14]:
print(matrixSum)
print(matrixProd)

[[ 0 -2 -3]
 [ 0  3  1]
 [-1 -1 -3]]
[[ 1  0  7]
 [-1 -3 -4]
 [ 1  2  3]]
